name: strapi-blogs-uat
on:
    push:
        branches:
            - main

jobs:
    strapi-blogs-uat:
        runs-on: ubuntu-latest

        permissions:
            id-token: write
            contents: read

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            # Authenticate to Google Cloud using workload identity federation
            - id: 'auth'
              name: 'Obtain access token by using workload identity federation'
              uses: 'google-github-actions/auth@v0'

              with:
                  create_credentials_file: true
                  token_format: access_token
                  workload_identity_provider: projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc-provider
                  service_account: github-actions-service-account@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com

            - name: Connect to Artifact Registry
              run: |-
                  echo ${{ steps.auth.outputs.access_token }} | docker login -u oauth2accesstoken --password-stdin https://${{ secrets.GCP_REPOSITORY_REGION }}-docker.pkg.dev

            - name: Build Docker Image
              run: docker build --no-cache -t asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/one5c2-non-prod-infra/${{ secrets.GCP_IMAGE_NAME }}:$GITHUB_REF_NAME-$GITHUB_SHA .

            - uses: actions/checkout@v2
            - name: Set env
              run: echo "GITHUB_BRANCH=$(echo $GITHUB_REF_NAME-$GITHUB_SHA)" >> $GITHUB_ENV

            - name: Push Docker Image to Artifact Registry
              run: |-
                  docker push asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/one5c2-non-prod-infra/${{ secrets.GCP_IMAGE_NAME }}:$GITHUB_REF_NAME-$GITHUB_SHA

                  git clone https://${{ secrets.GCP_GITHUB_USER }}:${{ secrets.GCP_GITHUB_TOKEN }}@github.com/finallykun9320/strapi-gitops

                  cd strapi-gitops

                  git checkout non-prod

                  git config user.name "$GITHUB_ACTOR"
                  git config user.email "$GITHUB_ACTOR@gmail.com"

                  yq e '.spec.template.spec.containers[0].image = "asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/one5c2-non-prod-infra/${{ secrets.GCP_IMAGE_NAME }}:${{ env.GITHUB_BRANCH }}"' -i deployment.apps/strapi-blogs.yaml

                  git add .
                  git commit -m "updating newer image"  
                  git push --set-upstream origin non-prod
